version: "3.3"
services: 
    step_one_unzip:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./wait-for.sh/:/app/wait-for.sh
            - ./src/:/app/src/
            - ./zip/:/app/zip/
            - ./extract/:/app/extract/
            - ./node_modules/:/app/node_modules/
        command: ["./wait-for.sh", "rabbitmq:5672", "--", "npm", "run", "step-one"]
        depends_on: 
            - rabbitmq

    step_two_convert:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./wait-for.sh/:/app/wait-for.sh
            - ./src/:/app/src/
            - ./zip/:/app/zip/
            - ./extract/:/app/extract/
            - ./node_modules/:/app/node_modules/
        command: ["./wait-for.sh", "rabbitmq:5672", "--", "npm", "run", "step-two"]
        depends_on: 
            - rabbitmq    

    step_three_upload:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./wait-for.sh/:/app/wait-for.sh
            - ./src/:/app/src/
            - ./zip/:/app/zip/
            - ./extract/:/app/extract/
            - ./node_modules/:/app/node_modules/
        command: ["./wait-for.sh", "rabbitmq:5672", "--", "npm", "run", "step-three"]
        depends_on: 
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3-management
        ports: 
            - 5672:5672
            - 15672:15672
