version: "3.3"
services: 
    consumer_producer:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./wait-for.sh/:/app/wait-for.sh
            - ./src/:/app/src/
            - ./node_modules/:/app/node_modules/
        command: ["./wait-for.sh", "rabbitmq:5672", "--", "npm", "run", "watch"]
        depends_on: 
            - rabbitmq
    consumer_consumer:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./wait-for.sh/:/app/wait-for.sh
            - ./src/:/app/src/
            - ./node_modules/:/app/node_modules/
        command: ["./wait-for.sh", "rabbitmq:5672", "--", "npm", "run", "watch"]
        depends_on: 
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3-management
        ports: 
            - 5672:5672
            - 15672:15672
